name: integration

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python Version
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Env Set Up
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --editable .
      - name: Run Tests
        run: |
          pip install -r requirements_dev.txt
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml
          pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

  flake8-py3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      - name: Run flake8
        run: |
          pip install flake8
          flake8 --version
          flake8 ./
